[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "npx prisma db push && node prisma/seed.js && node src/index.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
